parameters:
  version: ''

jobs:
- job: build
  displayName: 'standard'
  pool:
    vmImage: ubuntu-latest
  strategy:
    maxParallel: 10
    matrix:
      windows:
        BuildSuffix: 'windows-mingw'
        ScriptFolder: 'windows'
        containerImage: 'citraemu/build-environments:linux-mingw'
      linux:
        BuildSuffix: 'linux'
        ScriptFolder: 'linux'
        containerImage: 'citraemu/build-environments:linux-fresh'
  container: $[ variables['containerImage'] ]
  steps:
  - template: ./sync-source.yml
    parameters:
      artifactSource: ${{ parameters.artifactSource }}
      needSubmodules: 'true'
  - template: ./build-single.yml
    parameters:
      artifactSource: 'false'
      cache: $(parameters.cache)
      version: $(parameters.version)
