jobs:
- job: merge
  displayName: 'pull requests'
  steps:
  - checkout: self
    submodules: recursive
  - template: ./mergebot.yml
    parameters:
      matchLabel: '$(BuildName)-merge'
  - task: ArchiveFiles@2
    displayName: 'Package Source'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: '7z'
      archiveFile: '$(Build.ArtifactStagingDirectory)/citra-$(BuildName)-source.7z'
  - task: PublishPipelineArtifact@1
    displayName: 'Upload Artifacts'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/citra-$(BuildName)-source.7z'
      artifact: 'citra-$(BuildName)-source'
      replaceExistingArchive: true
- job: upload_source
  displayName: 'upload'
  condition: eq(variables['Build.Repository.Name'], 'citra-emu/citra')
  dependsOn: merge
  steps:
  - template: ./sync-source.yml
    parameters:
      artifactSource: 'true'
      needSubmodules: 'true'
  - script: chmod a+x $(System.DefaultWorkingDirectory)/.ci/scripts/merge/citrabot-git-config.sh && $(System.DefaultWorkingDirectory)/.ci/scripts/merge/citrabot-git-config.sh
    displayName: 'Apply Git Configuration'
  - script: git remote add other $(GitRepoPushChangesURL)
    displayName: 'Register Repository'
  - script: git push --force other HEAD:$(GitPushBranch)
    displayName: 'Update Code'
