trigger:
  tags:
    include: ['*']

resources:
  containers:
    - container: linux_flatpak
      image: "citraemu/build-environments:linux-flatpak"
      options: --privileged

jobs:
# LinuxFlatPak build
- job: LinuxFlatPak

  pool:
    vmImage: 'ubuntu-16.04'
  container: linux_flatpak
  steps:
  - bash: |
      echo "Tagname: ${TAGNAME}"
    env:
      TAGNAME: $(tagname)
  - bash: /bin/bash -ex ./.travis/linux-flatpak/generate-data.sh
    # set tx_token variable in the control panel and uncomment the following
    # env:
    #   TRANSIFEX_API_TOKEN: $(tx_token)
    displayName: 'Generate Flatpak metadata'
  - bash: /bin/bash -ex ./.travis/linux-flatpak/docker.sh
    displayName: 'Build Citra Flatpak'
    # Azure pipeline's condition expression is very weird
    # the following means:
    # Build.SourceBranch == 'refs/heads/master' && Build.Repository.Uri == 'citra-emu/citra' && PUSH EVENT (IndividualCI)
    # also, 'Build.Repository.Name' is not available prior to the 'steps' section
  # condition: eq(variables['System.TeamProjectId'], '378e0e5c-b2fc-4735-a473-fc2d60e2493b')
