trigger:
- master

stages:
- stage: merge
  displayName: 'merge'
  jobs:
  - template: ./templates/merge.yml
- stage: format
  dependsOn: merge
  displayName: 'format'
  jobs:
  - job: format
    displayName: 'clang'
    # container: 'citraemu/build-environments:linux-clang-format'
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: ./templates/format-check.yml
- stage: build
  displayName: 'build'
  dependsOn: format
  jobs:
  - template: ./templates/build-standard.yml
    parameters:
      cache: 'true'
